const sidebars = {
  foundationSidebar: [
    {
      type: 'autogenerated',
      dirName: 'foundation',
    },
  ],

  installationSidebar: [
    {
      type: 'autogenerated',
      dirName: 'installation',
    },
  ],

  drfSidebar: [
    {
      type: 'autogenerated',
      dirName: 'drf',
    },
  ],
};

export default sidebars;
