const sidebars = {
  foundationSidebar: [
    {
      type: 'autogenerated',
      dirName: 'foundations',
    },
  ],
  coreSidebar: [
    {
      type: 'autogenerated',
      dirName: 'core',
    },
  ],

  drfSidebar: [
    {
      type: 'autogenerated',
      dirName: 'drf',
    },
  ],

  relationshipSidebar: [
    {
      type: 'autogenerated',
      dirName: 'relationships',
    },
  ],

  routingSidebar: [
    {
      type: 'autogenerated',
      dirName: 'routing',
    },
  ],

  authSidebar: [
    {
      type: 'autogenerated',
      dirName: 'auth',
    },
  ],

  optimizationSidebar: [
    {
      type: 'autogenerated',
      dirName: 'optimization',
    },
  ],

  automationSidebar: [
    {
      type: 'autogenerated',
      dirName: 'automation',
    },
  ],
  deploySidebar: [
    {
      type: 'autogenerated',
      dirName: 'deploy',
    },
  ],
  agentSidebar: [
    {
      type: 'autogenerated',
      dirName: 'agents',
    },
  ],

};

export default sidebars;
